# Generated by Django 2.2.5 on 2019-09-26 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nlp', '0002_textuploaddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique ID across all user texts', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=240)),
                ('fulltext', models.TextField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
