# Generated by Django 2.2.5 on 2020-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_auto_20200219_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtext',
            name='fulltext',
            field=models.TextField(max_length=1000000),
        ),
    ]
