# Generated by Django 2.2.5 on 2019-09-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_uploadtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtext',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
