# Generated by Django 2.2.5 on 2019-10-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_uploadtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textinstance',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='textinstance',
            name='text',
        ),
        migrations.RemoveField(
            model_name='textuploaddb',
            name='user',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='TextInstance',
        ),
        migrations.DeleteModel(
            name='TextUploadDB',
        ),
    ]
