# Generated by Django 2.2.5 on 2019-10-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_auto_20191002_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtext',
            name='fulltext',
            field=models.TextField(max_length=100000),
        ),
    ]
