# Generated by Django 2.2.5 on 2019-11-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0005_auto_20191025_1311'),
        ('nlp', '0004_auto_20190926_1618'),
    ]

    operations = [
    ]
