# Generated by Django 2.2.5 on 2020-02-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0006_merge_20191101_1400'),
        ('nlp', '0007_auto_20191206_1217'),
    ]

    operations = [
    ]
