# Generated by Django 2.2.5 on 2020-02-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0009_bytetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
            ],
        ),
    ]
